### PR TITLE
added tsunami notebooks and associated data

### PR DESCRIPTION
**Pull request by rjleveque**
@acannistra: I organized these with the notebooks and data in separate directories similar to the organization of the `vector` directory.  You might want to do the same with your notebooks and data but then paths will change to where the data is.  Ok with me to leave as is too.

@lsetiawan: The `Chile2010_tsunami.ipynb` doesn't run on cloudmaven currently because basemap isn't included in the `Visualizationenv` kernel.

### CODE REVIEW

**Comment by lsetiawan** [comment]
> @lsetiawan: The Chile2010_tsunami.ipynb doesn't run on cloudmaven currently because basemap isn't included in the Visualizationenv kernel.

Thanks for letting me know @rjleveque. I have added basemap in. Please update your `environment.yml` if you have one.

```bash
$ conda list -n visualizationenv | grep basemap
basemap                   1.1.0                    py36_2    conda-forge
```

**Comment by rjleveque** [comment]
@lsetiawan: Now basemap is there but `ipywidgets` aren't.  I thought both were in the `environment.yml` file I sent this morning?

**Comment by lsetiawan** [comment]
@rjleveque I didn't create `Visualizationenv`. I assumed it was not created from the same `environment.yml`. Could you please add your `environment.yml` to this repo. I'll try reinstalling your tutorial environment. Thanks.

**Comment by rjleveque** [comment]
@lsetiawan: Thanks, it's now in this PR.

**Comment by acannistra** [comment]
@rjleveque OK, I'll get on that.

**Comment by lsetiawan** [comment]
@rjleveque I've installed your environment, now we just gotta wait for @amandalehr to update the kernel. Thanks!

**Comment by lsetiawan** [comment]
This PR also relates to #3

**Pull request merged**
