### PR TITLE
first cut at ndarrays_intro

### PR DESCRIPTION
**Pull request by jhamman**
Not ready to be merged yet. Just putting this up here to show progress and get any initial comments.

cc @aaarendt

### CODE REVIEW

**Comment by lsetiawan** [comment]
@jhamman No need for Dockerfile this year, but thanks anyways! Also thanks for using this repo for your notebooks :)

**Comment by aaarendt** [comment]
looks great so far. What do you think about incorporating the new regionmask to handle the masking stuff near the end?

**Comment by jhamman** [comment]
Sure. I was planning on having a `ndarrays_advanced` notebook where people can play around with a few packages built on xarray.

**Comment by lsetiawan** [comment]
@jhamman Is this ready to be merged?

**Comment by jhamman** [comment]
@lsetiawan - can you merge and stage?

**Pull request merged**
